<?php

namespace App\Http\Controllers;

use App\Models\SuiviPrepa;
use Illuminate\Http\Request;

class SuiviPrepaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        try {

            SuiviPrepa::upsert([
                [
                    "id" => 1,
                    "label" => "Date",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->date_un,
                    "deux" => $request->date_deux,
                    "trois" => $request->date_trois,
                    "quatre" => $request->date_quatre,
                    "cinq" => $request->date_cinq,
                    "six" => $request->date_six,
                    "sept" => $request->date_sept,
                    "huit" => $request->date_huit,
                    "neuf" => $request->date_neuf,
                    "dix" => $request->date_dix,
                ],
                [
                    "id" => 2,
                    "label" => "Encadrant(e)",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->encadrant_un,
                    "deux" => $request->encadrant_deux,
                    "trois" => $request->encadrant_trois,
                    "quatre" => $request->encadrant_quatre,
                    "cinq" => $request->encadrant_cinq,
                    "six" => $request->encadrant_six,
                    "sept" => $request->encadrant_sept,
                    "huit" => $request->encadrant_huit,
                    "neuf" => $request->encadrant_neuf,
                    "dix" => $request->encadrant_dix,
                ],
                [
                    "id" => 3,
                    "label" => "Profondeur d'exercice",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->profondeur_un,
                    "deux" => $request->profondeur_deux,
                    "trois" => $request->profondeur_trois,
                    "quatre" => $request->profondeur_quatre,
                    "cinq" => $request->profondeur_cinq,
                    "six" => $request->profondeur_six,
                    "sept" => $request->profondeur_sept,
                    "huit" => $request->profondeur_huit,
                    "neuf" => $request->profondeur_neuf,
                    "dix" => $request->profondeur_dix,
                ],
                [
                    "id" => 4,
                    "label" => "Lestage",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->lestage_un,
                    "deux" => $request->lestage_deux,
                    "trois" => $request->lestage_trois,
                    "quatre" => $request->lestage_quatre,
                    "cinq" => $request->lestage_cinq,
                    "six" => $request->lestage_six,
                    "sept" => $request->lestage_sept,
                    "huit" => $request->lestage_huit,
                    "neuf" => $request->lestage_neuf,
                    "dix" => $request->lestage_dix,
                ],
                [
                    "id" => 5,
                    "label" => "Autonomie dans l'équipement",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->autonomie_un,
                    "deux" => $request->autonomie_deux,
                    "trois" => $request->autonomie_trois,
                    "quatre" => $request->autonomie_quatre,
                    "cinq" => $request->autonomie_cinq,
                    "six" => $request->autonomie_six,
                    "sept" => $request->autonomie_sept,
                    "huit" => $request->autonomie_huit,
                    "neuf" => $request->autonomie_neuf,
                    "dix" => $request->autonomie_dix,
                ],
                [
                    "id" => 6,
                    "label" => "Vérification de la pression",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->verification_un,
                    "deux" => $request->verification_deux,
                    "trois" => $request->verification_trois,
                    "quatre" => $request->verification_quatre,
                    "cinq" => $request->verification_cinq,
                    "six" => $request->verification_six,
                    "sept" => $request->verification_sept,
                    "huit" => $request->verification_huit,
                    "neuf" => $request->verification_neuf,
                    "dix" => $request->verification_dix,
                ],
                [
                    "id" => 7,
                    "label" => "Bon fonctionnement du matériel",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->fonctionnement_un,
                    "deux" => $request->fonctionnement_deux,
                    "trois" => $request->fonctionnement_trois,
                    "quatre" => $request->fonctionnement_quatre,
                    "cinq" => $request->fonctionnement_cinq,
                    "six" => $request->fonctionnement_six,
                    "sept" => $request->fonctionnement_sept,
                    "huit" => $request->fonctionnement_huit,
                    "neuf" => $request->fonctionnement_neuf,
                    "dix" => $request->fonctionnement_dix,
                ],
                [
                    "id" => 8,
                    "label" => "Purger et gonfler en surface",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->purger_un,
                    "deux" => $request->purger_deux,
                    "trois" => $request->purger_trois,
                    "quatre" => $request->purger_quatre,
                    "cinq" => $request->purger_cinq,
                    "six" => $request->purger_six,
                    "sept" => $request->purger_sept,
                    "huit" => $request->purger_huit,
                    "neuf" => $request->purger_neuf,
                    "dix" => $request->purger_dix,
                ],
                [
                    "id" => 9,
                    "label" => "Saut Droit,*Bascule Arriére*, PMT 100 M",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->saut_droit_un,
                    "deux" => $request->saut_droit_deux,
                    "trois" => $request->saut_droit_trois,
                    "quatre" => $request->saut_droit_quatre,
                    "cinq" => $request->saut_droit_cinq,
                    "six" => $request->saut_droit_six,
                    "sept" => $request->saut_droit_sept,
                    "huit" => $request->saut_droit_huit,
                    "neuf" => $request->saut_droit_neuf,
                    "dix" => $request->saut_droit_dix,
                ],
                [
                    "id" => 10,
                    "label" => "Capelé 50 M",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->capele_un,
                    "deux" => $request->capele_deux,
                    "trois" => $request->capele_trois,
                    "quatre" => $request->capele_quatre,
                    "cinq" => $request->capele_cinq,
                    "six" => $request->capele_six,
                    "sept" => $request->capele_sept,
                    "huit" => $request->capele_huit,
                    "neuf" => $request->capele_neuf,
                    "dix" => $request->capele_dix,
                ],
                [
                    "id" => 11,
                    "label" => "Capelage - décapelage",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->capelage_un,
                    "deux" => $request->capelage_deux,
                    "trois" => $request->capelage_trois,
                    "quatre" => $request->capelage_quatre,
                    "cinq" => $request->capelage_cinq,
                    "six" => $request->capelage_six,
                    "sept" => $request->capelage_sept,
                    "huit" => $request->capelage_huit,
                    "neuf" => $request->capelage_neuf,
                    "dix" => $request->capelage_dix,
                ],
                [
                    "id" => 12,
                    "label" => "Palmage en surface dorsal, ventral et sustentation",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->palmage_en_surface_un,
                    "deux" => $request->palmage_en_surface_deux,
                    "trois" => $request->palmage_en_surface_trois,
                    "quatre" => $request->palmage_en_surface_quatre,
                    "cinq" => $request->palmage_en_surface_cinq,
                    "six" => $request->palmage_en_surface_six,
                    "sept" => $request->palmage_en_surface_sept,
                    "huit" => $request->palmage_en_surface_huit,
                    "neuf" => $request->palmage_en_surface_neuf,
                    "dix" => $request->palmage_en_surface_dix,
                ],
                [
                    "id" => 13,
                    "label" => "Palmage en immersion",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->palmage_en_immersion_un,
                    "deux" => $request->palmage_en_immersion_deux,
                    "trois" => $request->palmage_en_immersion_trois,
                    "quatre" => $request->palmage_en_immersion_quatre,
                    "cinq" => $request->palmage_en_immersion_cinq,
                    "six" => $request->palmage_en_immersion_six,
                    "sept" => $request->palmage_en_immersion_sept,
                    "huit" => $request->palmage_en_immersion_huit,
                    "neuf" => $request->palmage_en_immersion_neuf,
                    "dix" => $request->palmage_en_immersion_dix,
                ],
                [
                    "id" => 14,
                    "label" => "Phoque/Canard",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->phoque_un,
                    "deux" => $request->phoque_deux,
                    "trois" => $request->phoque_trois,
                    "quatre" => $request->phoque_quatre,
                    "cinq" => $request->phoque_cinq,
                    "six" => $request->phoque_six,
                    "sept" => $request->phoque_sept,
                    "huit" => $request->phoque_huit,
                    "neuf" => $request->phoque_neuf,
                    "dix" => $request->phoque_dix,
                ],
                [
                    "id" => 15,
                    "label" => "Utilisation détendeur en surface",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->utilisation_detendeur_un,
                    "deux" => $request->utilisation_detendeur_deux,
                    "trois" => $request->utilisation_detendeur_trois,
                    "quatre" => $request->utilisation_detendeur_quatre,
                    "cinq" => $request->utilisation_detendeur_cinq,
                    "six" => $request->utilisation_detendeur_six,
                    "sept" => $request->utilisation_detendeur_sept,
                    "huit" => $request->utilisation_detendeur_huit,
                    "neuf" => $request->utilisation_detendeur_neuf,
                    "dix" => $request->utilisation_detendeur_dix,
                ],
                [
                    "id" => 16,
                    "label" => "Stabilisation palier",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->stabilisation_un,
                    "deux" => $request->stabilisation_deux,
                    "trois" => $request->stabilisation_trois,
                    "quatre" => $request->stabilisation_quatre,
                    "cinq" => $request->stabilisation_cinq,
                    "six" => $request->stabilisation_six,
                    "sept" => $request->stabilisation_sept,
                    "huit" => $request->stabilisation_huit,
                    "neuf" => $request->stabilisation_neuf,
                    "dix" => $request->stabilisation_dix,
                ],
                [
                    "id" => 17,
                    "label" => "Ventilation en immersion",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->ventilation_immersion_un,
                    "deux" => $request->ventilation_immersion_deux,
                    "trois" => $request->ventilation_immersion_trois,
                    "quatre" => $request->ventilation_immersion_quatre,
                    "cinq" => $request->ventilation_immersion_cinq,
                    "six" => $request->ventilation_immersion_six,
                    "sept" => $request->ventilation_immersion_sept,
                    "huit" => $request->ventilation_immersion_huit,
                    "neuf" => $request->ventilation_immersion_neuf,
                    "dix" => $request->ventilation_immersion_dix,
                ],
                [
                    "id" => 18,
                    "label" => "REC 5m",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->rec_un,
                    "deux" => $request->rec_deux,
                    "trois" => $request->rec_trois,
                    "quatre" => $request->rec_quatre,
                    "cinq" => $request->rec_cinq,
                    "six" => $request->rec_six,
                    "sept" => $request->rec_sept,
                    "huit" => $request->rec_huit,
                    "neuf" => $request->rec_neuf,
                    "dix" => $request->rec_dix,
                ],
                [
                    "id" => 19,
                    "label" => "LRE",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->lre_un,
                    "deux" => $request->lre_deux,
                    "trois" => $request->lre_trois,
                    "quatre" => $request->lre_quatre,
                    "cinq" => $request->lre_cinq,
                    "six" => $request->lre_six,
                    "sept" => $request->lre_sept,
                    "huit" => $request->lre_huit,
                    "neuf" => $request->lre_neuf,
                    "dix" => $request->lre_dix,
                ],
                [
                    "id" => 20,
                    "label" => "VDM",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->vdm_un,
                    "deux" => $request->vdm_deux,
                    "trois" => $request->vdm_trois,
                    "quatre" => $request->vdm_quatre,
                    "cinq" => $request->vdm_cinq,
                    "six" => $request->vdm_six,
                    "sept" => $request->vdm_sept,
                    "huit" => $request->vdm_huit,
                    "neuf" => $request->vdm_neuf,
                    "dix" => $request->vdm_dix,
                ],
                [
                    "id" => 21,
                    "label" => "Ventilation sur tuba/Vidage du tuba",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->ventilation_tuba_un,
                    "deux" => $request->ventilation_tuba_deux,
                    "trois" => $request->ventilation_tuba_trois,
                    "quatre" => $request->ventilation_tuba_quatre,
                    "cinq" => $request->ventilation_tuba_cinq,
                    "six" => $request->ventilation_tuba_six,
                    "sept" => $request->ventilation_tuba_sept,
                    "huit" => $request->ventilation_tuba_huit,
                    "neuf" => $request->ventilation_tuba_neuf,
                    "dix" => $request->ventilation_tuba_dix,
                ],
                [
                    "id" => 22,
                    "label" => "Poumon-ballast",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->poumon_ballast_un,
                    "deux" => $request->poumon_ballast_deux,
                    "trois" => $request->poumon_ballast_trois,
                    "quatre" => $request->poumon_ballast_quatre,
                    "cinq" => $request->poumon_ballast_cinq,
                    "six" => $request->poumon_ballast_six,
                    "sept" => $request->poumon_ballast_sept,
                    "huit" => $request->poumon_ballast_huit,
                    "neuf" => $request->poumon_ballast_neuf,
                    "dix" => $request->poumon_ballast_dix,
                ],
                [
                    "id" => 23,
                    "label" => "Gestion du gilet en immersion/ gestion du gilet en surface",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->gestion_gilet_un,
                    "deux" => $request->gestion_gilet_deux,
                    "trois" => $request->gestion_gilet_trois,
                    "quatre" => $request->gestion_gilet_quatre,
                    "cinq" => $request->gestion_gilet_cinq,
                    "six" => $request->gestion_gilet_six,
                    "sept" => $request->gestion_gilet_sept,
                    "huit" => $request->gestion_gilet_huit,
                    "neuf" => $request->gestion_gilet_neuf,
                    "dix" => $request->gestion_gilet_dix,
                ],
                [
                    "id" => 24,
                    "label" => "Maitrise de la vitesse de remontée",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->maitrise_vitesse_un,
                    "deux" => $request->maitrise_vitesse_deux,
                    "trois" => $request->maitrise_vitesse_trois,
                    "quatre" => $request->maitrise_vitesse_quatre,
                    "cinq" => $request->maitrise_vitesse_cinq,
                    "six" => $request->maitrise_vitesse_six,
                    "sept" => $request->maitrise_vitesse_sept,
                    "huit" => $request->maitrise_vitesse_huit,
                    "neuf" => $request->maitrise_vitesse_neuf,
                    "dix" => $request->maitrise_vitesse_dix,
                ],
                [
                    "id" => 25,
                    "label" => "Tenue d'un palier et pour tour d'horizon",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->tenue_palier_un,
                    "deux" => $request->tenue_palier_deux,
                    "trois" => $request->tenue_palier_trois,
                    "quatre" => $request->tenue_palier_quatre,
                    "cinq" => $request->tenue_palier_cinq,
                    "six" => $request->tenue_palier_six,
                    "sept" => $request->tenue_palier_sept,
                    "huit" => $request->tenue_palier_huit,
                    "neuf" => $request->tenue_palier_neuf,
                    "dix" => $request->tenue_palier_dix,
                ],
                [
                    "id" => 26,
                    "label" => "Ça va/ ça ne va pas",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->cava_un,
                    "deux" => $request->cava_deux,
                    "trois" => $request->cava_trois,
                    "quatre" => $request->cava_quatre,
                    "cinq" => $request->cava_cinq,
                    "six" => $request->cava_six,
                    "sept" => $request->cava_sept,
                    "huit" => $request->cava_huit,
                    "neuf" => $request->cava_neuf,
                    "dix" => $request->cava_dix,
                ],
                [
                    "id" => 27,
                    "label" => "Surveiller et donner sa pression",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->surveiller_un,
                    "deux" => $request->surveiller_deux,
                    "trois" => $request->surveiller_trois,
                    "quatre" => $request->surveiller_quatre,
                    "cinq" => $request->surveiller_cinq,
                    "six" => $request->surveiller_six,
                    "sept" => $request->surveiller_sept,
                    "huit" => $request->surveiller_huit,
                    "neuf" => $request->surveiller_neuf,
                    "dix" => $request->surveiller_dix,
                ],
                [
                    "id" => 28,
                    "label" => "Echange d'embout/ Octopus",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->echange_un,
                    "deux" => $request->echange_deux,
                    "trois" => $request->echange_trois,
                    "quatre" => $request->echange_quatre,
                    "cinq" => $request->echange_cinq,
                    "six" => $request->echange_six,
                    "sept" => $request->echange_sept,
                    "huit" => $request->echange_huit,
                    "neuf" => $request->echange_neuf,
                    "dix" => $request->echange_dix,
                ],
                [
                    "id" => 29,
                    "label" => "Mi- pression",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->mi_un,
                    "deux" => $request->mi_deux,
                    "trois" => $request->mi_trois,
                    "quatre" => $request->mi_quatre,
                    "cinq" => $request->mi_cinq,
                    "six" => $request->mi_six,
                    "sept" => $request->mi_sept,
                    "huit" => $request->mi_huit,
                    "neuf" => $request->mi_neuf,
                    "dix" => $request->mi_dix,
                ],
                [
                    "id" => 30,
                    "label" => "Réserve",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->reserve_un,
                    "deux" => $request->reserve_deux,
                    "trois" => $request->reserve_trois,
                    "quatre" => $request->reserve_quatre,
                    "cinq" => $request->reserve_cinq,
                    "six" => $request->reserve_six,
                    "sept" => $request->reserve_sept,
                    "huit" => $request->reserve_huit,
                    "neuf" => $request->reserve_neuf,
                    "dix" => $request->reserve_dix,
                ],
                [
                    "id" => 31,
                    "label" => "Fin de plongée/ fin d'exercice",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->fin_plongee_un,
                    "deux" => $request->fin_plongee_deux,
                    "trois" => $request->fin_plongee_trois,
                    "quatre" => $request->fin_plongee_quatre,
                    "cinq" => $request->fin_plongee_cinq,
                    "six" => $request->fin_plongee_six,
                    "sept" => $request->fin_plongee_sept,
                    "huit" => $request->fin_plongee_huit,
                    "neuf" => $request->fin_plongee_neuf,
                    "dix" => $request->fin_plongee_dix,
                ],
                [
                    "id" => 32,
                    "label" => "Panne d'air/ Intervention en relais",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->panne_air_un,
                    "deux" => $request->panne_air_deux,
                    "trois" => $request->panne_air_trois,
                    "quatre" => $request->panne_air_quatre,
                    "cinq" => $request->panne_air_cinq,
                    "six" => $request->panne_air_six,
                    "sept" => $request->panne_air_sept,
                    "huit" => $request->panne_air_huit,
                    "neuf" => $request->panne_air_neuf,
                    "dix" => $request->panne_air_dix,
                ],
                [
                    "id" => 33,
                    "label" => "Froid",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->froid_un,
                    "deux" => $request->froid_deux,
                    "trois" => $request->froid_trois,
                    "quatre" => $request->froid_quatre,
                    "cinq" => $request->froid_cinq,
                    "six" => $request->froid_six,
                    "sept" => $request->froid_sept,
                    "huit" => $request->froid_huit,
                    "neuf" => $request->froid_neuf,
                    "dix" => $request->froid_dix,
                ],
                [
                    "id" => 34,
                    "label" => "Essoufflement",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->essoufflement_un,
                    "deux" => $request->essoufflement_deux,
                    "trois" => $request->essoufflement_trois,
                    "quatre" => $request->essoufflement_quatre,
                    "cinq" => $request->essoufflement_cinq,
                    "six" => $request->essoufflement_six,
                    "sept" => $request->essoufflement_sept,
                    "huit" => $request->essoufflement_huit,
                    "neuf" => $request->essoufflement_neuf,
                    "dix" => $request->essoufflement_dix,
                ],
                [
                    "id" => 35,
                    "label" => "Monter/descendre",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur,
                    "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->monter_un,
                    "deux" => $request->monter_deux,
                    "trois" => $request->monter_trois,
                    "quatre" => $request->monter_quatre,
                    "cinq" => $request->monter_cinq,
                    "six" => $request->monter_six,
                    "sept" => $request->monter_sept,
                    "huit" => $request->monter_huit,
                    "neuf" => $request->monter_neuf,
                    "dix" => $request->monter_dix,
                ],
                [
                    "id" => 36,
                    "label" => "Savoir se positionner / GP",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur, "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->savoir_un,
                    "deux" => $request->savoir_deux,
                    "trois" => $request->savoir_trois,
                    "quatre" => $request->savoir_quatre,
                    "cinq" => $request->savoir_cinq,
                    "six" => $request->savoir_six,
                    "sept" => $request->savoir_sept,
                    "huit" => $request->savoir_huit,
                    "neuf" => $request->savoir_neuf,
                    "dix" => $request->savoir_dix,
                ],
                [
                    "id" => 37,
                    "label" => "Apnée expiratoire sur 5m à l'horizontale utilisation de l'Octopus du GP",
                    "id_niveau" => $request->niveau,
                    "id_plongeur" => $request->plongeur, "id_encadrant" => $request->encadrant,
                    "saison" => $request->saison,
                    "un" => $request->apnee_un,
                    "deux" => $request->apnee_deux,
                    "trois" => $request->apnee_trois,
                    "quatre" => $request->apnee_quatre,
                    "cinq" => $request->apnee_cinq,
                    "six" => $request->apnee_six,
                    "sept" => $request->apnee_sept,
                    "huit" => $request->apnee_huit,
                    "neuf" => $request->apnee_neuf,
                    "dix" => $request->apnee_dix,
                ]
            ], ["id", "id_niveau", "id_plongeur"]);
            return redirect()->route('plongeurs.index');
        } catch (\Exception $err) {
            dd($err);
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(SuiviPrepa $suiviPrepa)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(SuiviPrepa $suiviPrepa)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, SuiviPrepa $suiviPrepa)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(SuiviPrepa $suiviPrepa)
    {
        //
    }
}